apiVersion: v1
kind: Service
metadata:
  name: pkad-ss
  labels:
    app: pkad-ss
spec:
  ports:
  - port: 80
    name: http
  clusterIP: None
  selector:
    app: pkad-ss
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pkad-ss
spec:
  serviceName: pkad-ss
  selector:
    matchLabels:
      app: pkad-ss
  replicas: 2
  template:
    metadata:
      labels:
        app: pkad-ss
    spec:
      containers:
      - name: pkad-ss
        image: poznajkubernetes/pkad:blue
        ports:
          - containerPort: 8080
            name: http
        resources: {}
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3